"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _service_list from './service-list.bones.json'
import _deal_list from './deal-list.bones.json'

registerBones({
  "service-list": _service_list,
  "deal-list": _deal_list,
})
